services:
  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v5.11.1
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - tyk
    volumes:
      - ./tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
      - ./middleware:/opt/tyk-gateway/middleware
      - ./certs:/opt/tyk-gateway/certs
      - ./policies:/opt/tyk-gateway/policies
    environment:
      - TYK_GW_SECRET=foo
    depends_on:
      - tyk-redis
  tyk-redis:
    image: redis:8.2.4-bookworm
    networks:
      - tyk
    ports:
      - 6379:6379

networks:
  tyk:
